name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        redis: [false, true]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --silent
        env:
          NODE_ENV: test
          # Only set REDIS_URL for the redis=true matrix entries
          REDIS_URL: ${{ matrix.redis && 'redis://localhost:6379' || '' }}
          # OPENAI_API_KEY is not required in tests; Responses client is faked


