name: Release

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.release.target_commitish == 'main') }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/open-assistants-api
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha

      - name: Extract release version
        if: ${{ github.event_name == 'release' }}
        id: release_meta
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build amd64 image tar
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/open-assistants-api:${{ steps.release_meta.outputs.version }} --output type=docker,dest=open-assistants-api_${{ steps.release_meta.outputs.version }}_linux-amd64.tar .

      - name: Upload image tar to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: open-assistants-api_${{ steps.release_meta.outputs.version }}_linux-amd64.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


